FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-stretch-build

WORKDIR /usr/src/app

# Declare arguments
ENV AWS_HOST=
ENV AWS_PORT=
ENV AWS_CLIENT_ID=
ENV CA_PATH=/usr/src/app/AmazonRootCA1.pem
ENV CERT_PATH=/data/wott/client.crt
ENV KEY_PATH=/data/wott/client.key
ENV MQTT_TOPIC=

RUN wget -q https://www.amazontrust.com/repository/AmazonRootCA1.pem
RUN pip install -U pip

COPY requirements.txt .
RUN pip install \
    --no-cache-dir \
    -r requirements.txt

COPY connect.py .

COPY start.sh /start.sh

CMD /start.sh

