FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-stretch-run
WORKDIR /usr/src/app
ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libssl-dev libffi-dev libltdl-dev curl && \
    apt-get clean

RUN mkdir -p /opt/wott/certs

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./
RUN python setup.py install

CMD wott-agent
