FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-stretch-build

WORKDIR /usr/src/app
ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends libssl-dev libffi-dev git-core && \
    apt-get clean

RUN pip install -U pip

# Don't pin releases yet
RUN pip install git+https://github.com/WoTTsecurity/agent.git@2c8bae828af5a17167ab31ff9385675dd99f09b5

# Balena specific path override
ENV CERT_PATH=/data/wott/certs

COPY start.sh /start.sh

CMD /start.sh
