FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.5-stretch-build


WORKDIR /usr/src/app
ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends libssl-dev libffi-dev git-core pkg-config libsystemd-dev && \
    apt-get clean
RUN pip3 install --upgrade setuptools pip

RUN pip3 install git+https://github.com/GreatFruitOmsk/agent.git@fix-snap

# Balena specific path override
ENV CERT_PATH=/data/wott/certs

COPY start.sh /start.sh

CMD /start.sh
