FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-stretch-build

WORKDIR /usr/src/app

# Declare required arguments
ENV DEVICE_ID=
ENV REGISTRY_ID=
ENV CLOUD_REGION=
ENV PROJECT_ID=

RUN wget -q https://raw.githubusercontent.com/GoogleCloudPlatform/python-docs-samples/master/iot/api-client/mqtt_example/cloudiot_mqtt_example.py && \
    wget -q https://raw.githubusercontent.com/GoogleCloudPlatform/python-docs-samples/master/iot/api-client/mqtt_example/requirements.txt && \
    wget -q https://pki.google.com/roots.pem
RUN pip install -U pip

# We need to pass on `--no-use-pep517` due to a bug in pip:
# https://github.com/pypa/pip/issues/6197

RUN pip install \
    --no-cache-dir \
    --no-use-pep517 \
    -r requirements.txt

COPY start.sh /start.sh

CMD /start.sh
